language: node_js
node_js:
- stable
before_install:
- npm install
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: So/+qEXP3NMjGltWODDL4ZgqLuqo7Z8tJy259vlCQubxzjm/sk+vyXG60rSp+fJ3naA3gPcBEKljEsMBJZG0AqS4nmNl6clzPBmhDpXRiwUsYS2hDXtbMavDkOf8NiQj/3LEA3CeGzMFkIDWoh6FXsnf/qHfYWk7sacxOaXgOQGsQB+7QUwwB+PZRGIjVatAEUYnbPW0fwFEmTKWIB0ulg8ysspVyx1XQHF7bEGPUrvyYPrB7RPS1KtPySTFHLo73e0ShhAxR+RmFhuaVY+8n1TgAhIitXwL8u+NKVNAclHkNtgopTgnHHyXP7kHZ8xTHDzL6rPXPujrrv4AYhMPtgVoYK0TdptS+hOi8jUhPpLcdX4+fxR8t7LS0rTQ0uwN3i72iW1+p6ckRXDNlflWy+HrbDO+/CCcRE1fMehHNvYpqGdksvUbozJgkSgXJPHdZaSe2ttxgEcNH5Wrp5VoXwkFQoSk7Hd2ckQf8exApmx4f6To0UCDxePRqdF4hUtxpsoTgvk0mjrKhYWqFBJgO+tCYWTUjRAksd6Lzn98DKBXldNTq3UeHC/1hIj9IA1xe4LjKzbnv5mE9qEUpd68cM0ZZrTN6Ouo0OeDaDnVNiqVHAuRS6miwXywqvMPU0s6XxOB+haUUHC+MxNx7OcmT9SBdYvGpc1ixdE2vXzcgFY=
  project: etabeta-810bc
env:
  global:
    secure: So/+qEXP3NMjGltWODDL4ZgqLuqo7Z8tJy259vlCQubxzjm/sk+vyXG60rSp+fJ3naA3gPcBEKljEsMBJZG0AqS4nmNl6clzPBmhDpXRiwUsYS2hDXtbMavDkOf8NiQj/3LEA3CeGzMFkIDWoh6FXsnf/qHfYWk7sacxOaXgOQGsQB+7QUwwB+PZRGIjVatAEUYnbPW0fwFEmTKWIB0ulg8ysspVyx1XQHF7bEGPUrvyYPrB7RPS1KtPySTFHLo73e0ShhAxR+RmFhuaVY+8n1TgAhIitXwL8u+NKVNAclHkNtgopTgnHHyXP7kHZ8xTHDzL6rPXPujrrv4AYhMPtgVoYK0TdptS+hOi8jUhPpLcdX4+fxR8t7LS0rTQ0uwN3i72iW1+p6ckRXDNlflWy+HrbDO+/CCcRE1fMehHNvYpqGdksvUbozJgkSgXJPHdZaSe2ttxgEcNH5Wrp5VoXwkFQoSk7Hd2ckQf8exApmx4f6To0UCDxePRqdF4hUtxpsoTgvk0mjrKhYWqFBJgO+tCYWTUjRAksd6Lzn98DKBXldNTq3UeHC/1hIj9IA1xe4LjKzbnv5mE9qEUpd68cM0ZZrTN6Ouo0OeDaDnVNiqVHAuRS6miwXywqvMPU0s6XxOB+haUUHC+MxNx7OcmT9SBdYvGpc1ixdE2vXzcgFY=
