language: node_js
node_js:
- stable
before_install:
- npm install
env:
  global:
    secure: l7wreBbxRcUCYM1w+6JRfkyMrAxtibcKd1wF1ejPGlglFyI63jeZ4nz5q+L4FzdI1qqu2o56adPnQANM8r11VVzsq6SscuPr2stN8Vx8oV9aMHkDandraeo9YFQ0dSu1c5F7VUUr3aYZCeG3EBK5zt+JpmYQItw6AYg9CN96qYqzSezaLgOpJ4N5lD6jLqoqdork/FF1ieezI3VMhImFJAtgtEchaNZp7XEDlLsGwPo46Vepi//w9W+hLeN0LjyRqEdWJcGOR6Pxa1o7HjmJA1WKkqq2lHtr3En1+kAdi2GCIJfPl/dS5Y2KKwDm9RteC1TdridLq241ry3B/aH41E8wNxUZoK9EXTW1Uj+7R3iW+8m5IjyDisvbT/I3rBlxmknN6mDzLkVwQnIQBcYTjnoVAEGG7WOUoNIXeCHwOYjLZF5vZnPkzmvKn04TKKpHKMfGjx0CyA/j7NlcCnkspDjevcAKCUaXPd1ToYkcEhY3MJFd7yLyI27zaQjYO7caDHd22ZnID3THfg7dpjzAuU5NP4fzgQpzxvRIeV+EveWiuYiN/Pk9vYCUNGwnbdPqU14hH0arFZSMiS5/xFskdeioEu2H8yqf+fPMp4shZM9C0UuMsMz1ZEmjaXKjWtH+isyaS7ZSSBgCtE483arUSWDMOWqI3zx6DIgiYLBj/1Q=
deploy:
  provider: firebase
  token:
    secure: "l7wreBbxRcUCYM1w+6JRfkyMrAxtibcKd1wF1ejPGlglFyI63jeZ4nz5q+L4FzdI1qqu2o56adPnQANM8r11VVzsq6SscuPr2stN8Vx8oV9aMHkDandraeo9YFQ0dSu1c5F7VUUr3aYZCeG3EBK5zt+JpmYQItw6AYg9CN96qYqzSezaLgOpJ4N5lD6jLqoqdork/FF1ieezI3VMhImFJAtgtEchaNZp7XEDlLsGwPo46Vepi//w9W+hLeN0LjyRqEdWJcGOR6Pxa1o7HjmJA1WKkqq2lHtr3En1+kAdi2GCIJfPl/dS5Y2KKwDm9RteC1TdridLq241ry3B/aH41E8wNxUZoK9EXTW1Uj+7R3iW+8m5IjyDisvbT/I3rBlxmknN6mDzLkVwQnIQBcYTjnoVAEGG7WOUoNIXeCHwOYjLZF5vZnPkzmvKn04TKKpHKMfGjx0CyA/j7NlcCnkspDjevcAKCUaXPd1ToYkcEhY3MJFd7yLyI27zaQjYO7caDHd22ZnID3THfg7dpjzAuU5NP4fzgQpzxvRIeV+EveWiuYiN/Pk9vYCUNGwnbdPqU14hH0arFZSMiS5/xFskdeioEu2H8yqf+fPMp4shZM9C0UuMsMz1ZEmjaXKjWtH+isyaS7ZSSBgCtE483arUSWDMOWqI3zx6DIgiYLBj/1Q="
  project: "etabeta-810bc"