language: node_js
node_js:
- stable
before_install:
- npm install
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: xZAfRRYtO9rWjfyty8GWjJYiUkm9Nn/Ziaqkh38KpXUKbXvUtZXjALoLnXRc+nDd27GD/has+apugH8sdWjxCh3A8XCdQ5JJxOco2SftY+qyBj4q+tbs1TueJfFShWzW0W4sB/Ryky4baN85m3fVtMXBgDo2Z9IP8Np42eDvXWZV/QDLWbwNEaVz06wEUFSwVlN42VI2DwO2G+gtjRS6y4ZT+sc/wH3BcixdQYOggPBDGo9rrUs2k/gX/i3v6KnN1VrSh6J06dd9j+D+fXrCD+iEKgtpPWwSub9mdIAYslNOWKcMh3qkXwV23tLS5ks5bnAsVMLH1Fqd4FAJJ/8dko84WmC+fi7Z84MTzW/zy8sfXgR8IyknWqVXCAWnNFjQ9/p/F0GixuRhzgk6VJaWTKHax3A0fEukqP3qK5kTPjcttkbIcSdj0lR7Ai1kDp3RShmYA7ASGjqLryacVEsTMobfD3PyBJh1xx87glB7lwAgjmsCt1Ty8GAYdNf4v39QtVM3djT8H/qxVtpSKIq0vuZhvpcw7HT0YdI3StikKEayVHyJyqb5qnVU9BYkPrdlX1SSEm2Mj/xGDEudCf9iQpKgdUJtAysV4Z+M7/VvyUPDQYPgLk+mahaGFoUUFJVfQ8Td8pkQN9FjkPdiVoEq4qmTTSfWWQnAsMArDz29YrA=
  project: etabeta-810bc
env:
  global:
  - secure: xZAfRRYtO9rWjfyty8GWjJYiUkm9Nn/Ziaqkh38KpXUKbXvUtZXjALoLnXRc+nDd27GD/has+apugH8sdWjxCh3A8XCdQ5JJxOco2SftY+qyBj4q+tbs1TueJfFShWzW0W4sB/Ryky4baN85m3fVtMXBgDo2Z9IP8Np42eDvXWZV/QDLWbwNEaVz06wEUFSwVlN42VI2DwO2G+gtjRS6y4ZT+sc/wH3BcixdQYOggPBDGo9rrUs2k/gX/i3v6KnN1VrSh6J06dd9j+D+fXrCD+iEKgtpPWwSub9mdIAYslNOWKcMh3qkXwV23tLS5ks5bnAsVMLH1Fqd4FAJJ/8dko84WmC+fi7Z84MTzW/zy8sfXgR8IyknWqVXCAWnNFjQ9/p/F0GixuRhzgk6VJaWTKHax3A0fEukqP3qK5kTPjcttkbIcSdj0lR7Ai1kDp3RShmYA7ASGjqLryacVEsTMobfD3PyBJh1xx87glB7lwAgjmsCt1Ty8GAYdNf4v39QtVM3djT8H/qxVtpSKIq0vuZhvpcw7HT0YdI3StikKEayVHyJyqb5qnVU9BYkPrdlX1SSEm2Mj/xGDEudCf9iQpKgdUJtAysV4Z+M7/VvyUPDQYPgLk+mahaGFoUUFJVfQ8Td8pkQN9FjkPdiVoEq4qmTTSfWWQnAsMArDz29YrA=
